library(lmtest)
library(forecast)
library(tseries)
ekspor <- read.csv2("D:/Data Tugas/DataARW/Nilai Ekspor.csv")
View(ekspor)
str(ekspor)
ts.plot(ekspor$Ekspor, main="Ekspor 2020-2023")

adf.test(ekspor$Ekspor)
acf(ekspor$Ekspor)
dlekspor3<-diff(log(ekspor$Ekspor))
dekspor3<-diff(ekspor$Ekspor)
plot.ts(dlekspor3)
plot.ts(dekspor3)
adf.test(dekspor3)
adf.test(dlekspor3)
acf(dekspor3)
pacf(dekspor3)

m1<-arima(ekspor$Ekspor,c(2,1,1))
summary(m1)
coeftest(m1)

m2<-arima(ekspor$Ekspor,c(2,1,0))
summary(m2)
coeftest(m2)

m3<-arima(ekspor$Ekspor,c(3,1,0))
summary(m3)
coeftest(m3)

tsdiag(m2)
forecast(m2)

library(lmtest)
library(forecast)
library(tseries)
saham <- read.csv("D:/Data Tugas/DataARW/saham2.csv")
str(saham)
ts.plot(saham$Close, main="Close 2022-2023")

adf.test(saham$Close)
acf(saham$Close)
dlekspor3<-diff(log(saham$Close))
dekspor3<-diff(saham$Close)
adf.test(dekspor3)
adf.test(dlekspor3)
acf(dlekspor3)
acf(dekspor3)
pacf(dekspor3)

m1<-arima(saham$Close,c(2,1,1))
summary(m1)
coeftest(m1)

m2<-arima(saham$Close,c(2,1,2))
summary(m2)
coeftest(m2)

m3<-arima(saham$Close,c(1,1,3))
summary(m3)
coeftest(m3)

m4<-arima(saham$Close,c(0,1,3))
summary(m4)
coeftest(m4)

tsdiag(m2)
forecast(m2)
arima <- c(2, 1, 0)
AutoArimaModel <- arima(dekspor3, order = arima)
print(AutoArimaModel)

library(lmtest)
library(forecast)
library(tseries)
saham <- read.csv2("D:/Data Tugas/DataARW/latihan.csv")
str(saham)
ts.plot(saham$Close, main="Close 2022-2023")
x<-as.numeric(saham$Close)
x
adf.test(x)
acf(x)
dlekspor3<-diff(log(x))
dekspor3<-diff(x)
adf.test(x)
adf.test(x)
acf(dlekspor3)
acf(dekspor3)
pacf(dekspor3)

m1<-arima(x,c(2,1,1))
summary(m1)
coeftest(m1)

m2<-arima(x,c(2,1,2))
summary(m2)
coeftest(m2)

m3<-arima(x,c(1,1,3))
summary(m3)
coeftest(m3)

m4<-arima(x,c(0,1,3))
summary(m4)
coeftest(m4)

tsdiag(m2)
forecast(m2)
arima <- c(2, 1, 0)
AutoArimaModel <- arima(dekspor3, order = arima)
print(AutoArimaModel)